CREATE DATABASE IF NOT EXISTS teste;
USE teste;
CREATE TABLE tabela1 (nome VARCHAR(255), id INT, PRIMARY KEY (id));
CREATE TABLE tabela2 (codigo INT, descricao VARCHAR(255), descricao2 VARCHAR(255));

ALTER TABLE tabela2 ADD fk INT;
ALTER TABLE tabela2 ADD CONSTRAINT fk FOREIGN KEY(fk) REFERENCES tabela1(id);
